name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run

name: slack_github_action
on: [push]
jobs:
  slack_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
            "text": "Git push done in the repo , Squibler "
            }
        env:
          SLACK_WEBHOOK_URL:https://hooks.slack.com/services/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}