name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Slack Notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'good' # Green color for success
          SLACK_ICON: https://imgur.com/kdD7Ifu
          SLACK_MESSAGE: 'Success Test Automation Report (Success) https://github.com/AqibGhaffar/Squibler/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'danger' # Red color for failure
          SLACK_ICON: https://imgur.com/kdD7Ifu
          SLACK_MESSAGE: 'Fail Test Automation Report (Failure) https://github.com/AqibGhaffar/Squibler/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       

  # slack_notifier:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Send notification on Slack using Webhooks
  #       uses: slackapi/slack-github-action@v1.24.0
  #       with:
  #         payload: |
  #           {
  #             "text": "Git push done in the repo, Squibler"   
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
